version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_DATABASE: financial_bank
    networks:
      - app_network
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: production
    networks:
      - app_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Admin*"
      MYSQL_DATABASE: financial_bank
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./financialBank.sql:/docker-entrypoint-initdb.d/financialBank.sql
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 10
      start_period: 30s  # Aumenté el tiempo para dar más margen al inicio
      timeout: 10s

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
